//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//


package net.opengis.gml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopoSurfacePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TopoSurfacePropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml}TopoSurface"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopoSurfacePropertyType", propOrder = {
    "topoSurface"
})
public class TopoSurfacePropertyType {

    @XmlElement(name = "TopoSurface", required = true)
    protected TopoSurfaceType topoSurface;

    /**
     * Gets the value of the topoSurface property.
     * 
     * @return
     *     possible object is
     *     {@link TopoSurfaceType }
     *     
     */
    public TopoSurfaceType getTopoSurface() {
        return topoSurface;
    }

    /**
     * Sets the value of the topoSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopoSurfaceType }
     *     
     */
    public void setTopoSurface(TopoSurfaceType value) {
        this.topoSurface = value;
    }

}
