//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 04:46:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nurc.nato.int/metocs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.geosolutions.geobatch.metocs.jaxb.model;

