//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//

package eu.europa.emsa.csndc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Array of auxiliary data related to the Oil Spill (for example images)
 * 
 * <p>
 * Java class for AuxiliaryDataReferenceArrayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuxiliaryDataReferenceArrayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auxiliaryData" type="{http://www.emsa.europa.eu/csndc}AuxiliaryDataReferenceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuxiliaryDataReferenceArrayType", propOrder = { "auxiliaryData" })
public class AuxiliaryDataReferenceArrayType {

    @XmlElement(required = true)
    protected List<AuxiliaryDataReferenceType> auxiliaryData;

    /**
     * Gets the value of the auxiliaryData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the auxiliaryData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAuxiliaryData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link AuxiliaryDataReferenceType }
     * 
     * 
     */
    public List<AuxiliaryDataReferenceType> getAuxiliaryData() {
        if (auxiliaryData == null) {
            auxiliaryData = new ArrayList<AuxiliaryDataReferenceType>();
        }
        return this.auxiliaryData;
    }

}
