//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//

package eu.europa.emsa.csndc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * GML files describing observed in the original satellite image
 * 
 * <p>
 * Java class for DetectedShipsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetectedShipsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.emsa.europa.eu/csndc}detectedShipReference" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetectedShipsType", propOrder = { "detectedShipReference" })
public class DetectedShipsType {

    @XmlElement(required = true)
    protected List<DetectedShipReferenceType> detectedShipReference;

    @XmlAttribute(required = true)
    protected BigInteger total;

    /**
     * List of references to the Ships detected in the scene Gets the value of the detectedShipReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the detectedShipReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDetectedShipReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DetectedShipReferenceType }
     * 
     * 
     */
    public List<DetectedShipReferenceType> getDetectedShipReference() {
        if (detectedShipReference == null) {
            detectedShipReference = new ArrayList<DetectedShipReferenceType>();
        }
        return this.detectedShipReference;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTotal(BigInteger value) {
        this.total = value;
    }

}
