//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//

package eu.europa.emsa.csndc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InSituInformationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InSituInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inSituValidation" type="{http://www.emsa.europa.eu/csndc}InSituValidationType"/>
 *         &lt;element name="inSituValidationBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InSituInformationType", propOrder = { "inSituValidation", "inSituValidationBody",
        "notes" })
public class InSituInformationType {

    @XmlElement(required = true)
    protected InSituValidationType inSituValidation;

    @XmlElement(required = true)
    protected String inSituValidationBody;

    protected String notes;

    /**
     * Gets the value of the inSituValidation property.
     * 
     * @return possible object is {@link InSituValidationType }
     * 
     */
    public InSituValidationType getInSituValidation() {
        return inSituValidation;
    }

    /**
     * Gets the value of the inSituValidationBody property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInSituValidationBody() {
        return inSituValidationBody;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the inSituValidation property.
     * 
     * @param value allowed object is {@link InSituValidationType }
     * 
     */
    public void setInSituValidation(InSituValidationType value) {
        this.inSituValidation = value;
    }

    /**
     * Sets the value of the inSituValidationBody property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInSituValidationBody(String value) {
        this.inSituValidationBody = value;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
