//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//

package eu.europa.emsa.csndc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OilSpillReferenceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OilSpillReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.emsa.europa.eu/csndc}identifier"/>
 *         &lt;element ref="{http://www.emsa.europa.eu/csndc}fileName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OilSpillReferenceType", propOrder = { "identifier", "fileName" })
public class OilSpillReferenceType {

    @XmlElement(required = true)
    protected String identifier;

    protected String fileName;

    /**
     * Reference to the GML file describing the OS feature
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Reference to the observed oil spill. This ID shall match with the uid of the Oil Spill feature described by GML file according to csndc_os.xsd
     * schema.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

}
