//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 10:49:44 AM CEST 
//

package eu.europa.emsa.csndc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Specify the data package attributes
 * 
 * <p>
 * Java class for PackageInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="packageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="packageType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="OS_WARNING"/>
 *               &lt;enumeration value="EO_PRODUCT"/>
 *               &lt;enumeration value="OS_NOTIFICATION"/>
 *               &lt;enumeration value="SAR_DERIVED"/>
 *               &lt;enumeration value="QUALITY_NOTIFICATION"/>
 *               &lt;enumeration value="QUALITY_REPORT"/>
 *               &lt;enumeration value="PROCESS_REQUEST"/>
 *               &lt;enumeration value="PROCESS_RESPONSE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="operationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TEST"/>
 *               &lt;enumeration value="NOMINAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataPackageDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageInfoType", propOrder = { "packageId", "packageType", "operationType",
        "dataPackageDescription" })
public class PackageInfoType {

    @XmlElement(required = true)
    protected String packageId;

    @XmlElement(required = true)
    protected String packageType;

    @XmlElement(required = true)
    protected String operationType;

    protected String dataPackageDescription;

    /**
     * Gets the value of the dataPackageDescription property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataPackageDescription() {
        return dataPackageDescription;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Gets the value of the packageId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * Gets the value of the packageType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the dataPackageDescription property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDataPackageDescription(String value) {
        this.dataPackageDescription = value;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Sets the value of the packageId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPackageId(String value) {
        this.packageId = value;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPackageType(String value) {
        this.packageType = value;
    }

}
